### ISSUE TITLE
SerializationException: Start of list found where not expected

### ISSUE THREAD

**Issue by bilalsha** [mpyw/cloudwatch-front-logger#9]
I have setup application correctly error log is being printed in cloudwatch logs but I am getting this exception when I load page.

I have added some screenshot for my settings and code.

<img width="744" alt="Screenshot 2021-07-05 at 11 50 40 AM" src="https://user-images.githubusercontent.com/6153951/124429750-b2802c80-dd87-11eb-8ac9-95d7391b8d82.png">

![Screenshot 2021-07-05 at 11 50 09 AM](https://user-images.githubusercontent.com/6153951/124429759-b57b1d00-dd87-11eb-9ba5-358095abe56d.png)

![Screenshot 2021-07-05 at 11 49 30 AM](https://user-images.githubusercontent.com/6153951/124429761-b613b380-dd87-11eb-865e-5c8831b3028c.png)

**Comment by mpyw** [comment]
@bilalsha I found out! `fingerprintjs`'s compatibility problem. (Also it looks to be renamed from `fingerprintjs2`)

- `v1.x`: https://github.com/fingerprintjs/fingerprintjs/tree/8382b6eeccdbbad9
- `master` (Currently `3.x`): https://github.com/fingerprintjs/fingerprintjs/tree/master

The usage of `get()` has been significantly changed.
